const Data = [
  {
    _id: "1",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/d2.jpeg",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 11,
  },
  {
    _id: "2",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s1.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 0,
  },
  {
    _id: "3",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s2.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "4",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s3.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "5",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s4.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "6",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s5.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "7",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s6.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "8",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s7.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "9",
    category: "Shirts",
    name: "Missing Shirt",
    img: "/images/s8.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "10",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s9.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "11",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s10.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "12",
    category: "Shirts",
    name: "Slim Shirt",
    img: "/images/s11.webp",
    brand: "Nike",
    price: 45,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Shirt",
    countInStock: 5,
  },
  {
    _id: "13",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p1.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "14",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p2.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "15",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p3.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "16",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p4.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "17",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p5.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "18",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p6.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "19",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p7.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "20",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p8.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "21",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p9.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "22",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p10.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
  {
    _id: "23",

    category: "Pants",
    name: "Slim Pants",
    img: "/images/p11.webp",
    brand: "Nike",
    price: 65,
    rating: 4.5,
    numReviews: 10,
    description: "Nice Pant",
    countInStock: 5,
  },
];

export default Data;
